services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - "reverse-proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/config:/etc/traefik"
      - "./traefik/logs:/var/log/traefik"

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - "reverse-proxy"
    volumes:
      # nginx global config
      - ./nginx/nginx.conf:/etc/nginx.conf:ro
      # nginx server configs
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      # nginx www sites folder
      - ./nginx/www:/var/www:ro
      # nginx logs
      - ./nginx/logs/access.log:/var/log/nginx/access.log
    labels:
      - "traefik.enable=false"

networks:
  reverse-proxy:
    name: "reverse-proxy"
    driver: bridge
