log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"

api:
  insecure: false
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "/etc/traefik/dynamic.yml"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: toombez.timurtokaev@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
